<?php

use Drupal\toolbar_manager\Entity\ToolbarItemSettings;
use Drupal\toolbar_manager\Entity\ToolbarLinkItem;
use Drupal\Core\Url;

/**
 * Implements hook_toolbar()
 */
function toolbar_manager_toolbar() {
  $toolbar_link_items = ToolbarLinkItem::loadMultipleSorted();
  $items = [];

  foreach ($toolbar_link_items as $toolbar_link_item) {
    $items[$toolbar_link_item->id] = [
      '#cache' => [
        'contexts' => [
          'user.permissions',
        ],
      ],
      '#type' => 'toolbar_item',
      'tab' => [
        '#type' => 'link',
        '#title' => $toolbar_link_item->text,
        '#url' => Url::fromUri(ToolbarLinkItem::getUserEnteredStringAsUri($toolbar_link_item->url)),
        '#attributes' => [
          'class' => [],
        ],
        '#cache' => [],
      ],
      '#wrapper_attributes' => [
        'class' => [],
      ],
      '#attached' => [
        'library' => [],
      ],
      '#weight' => $toolbar_link_item->weight,
    ];
  }

  return $items;
}

/**
 * Implements hook_toolbar_alter()
 */
function toolbar_manager_toolbar_alter(&$items) {
  $toolbar_items_settings = ToolbarItemSettings::loadMultipleSorted();
  foreach ($items as $id => $item) {
    $items[$id]['#original_tab'] = isset($items[$id]['tab']) ? $items[$id]['tab'] : NULL;

    if (isset($toolbar_items_settings[$id])) {
      if (!$toolbar_items_settings[$id]->enabled) {
        //unset($items[$id]);
        $items[$id]['tab']['#access'] = FALSE;
      }
      else {
        $items[$id]['#weight'] = (int) $toolbar_items_settings[$id]->weight;
      }

      if (!empty($toolbar_items_settings[$id]->custom_label) &&  isset($items[$id]['tab']['#type'])) {
        if ($items[$id]['tab']['#type'] == 'link' && isset($items[$id]['tab']['#title'])) {
          $items[$id]['tab']['#title'] = $toolbar_items_settings[$id]->custom_label;
        }
        else if ($items[$id]['tab']['#type'] == 'html_tag' && isset($items[$id]['tab']['#value'])) {
          $items[$id]['tab']['#value'] = $toolbar_items_settings[$id]->custom_label;
        }
      }
      if (!empty($toolbar_items_settings[$id]->css_classes) && in_array($items[$id]['tab']['#type'], ['link', 'html_tag'])) {
        $items[$id]['tab']['#attributes']['class'] = explode(' ', $toolbar_items_settings[$id]->css_classes);
      }
    }
  }
}
