<?php

use Drupal\toolbar_manager\Entity\ToolbarItemSettings;

/**
 * Implements hook_toolbar_alter()
 */
function toolbar_manager_toolbar_alter(&$items) {
  $toolbar_items_settings = ToolbarItemSettings::loadMultipleSorted();
  foreach ($items as $id => $item) {
    if (isset($toolbar_items_settings[$id])) {
      if (!$toolbar_items_settings[$id]->enabled) {
        //unset($items[$id]);
        $items[$id]['tab']['#access'] = FALSE;
      }
      else {
        $items[$id]['#weight'] = (int) $toolbar_items_settings[$id]->weight;
      }

      $items[$id]['#original_tab'] = $items[$id]['tab'];

      if (!empty($toolbar_items_settings[$id]->custom_label) &&  isset($items[$id]['tab']['#type'])) {
        if ($items[$id]['tab']['#type'] == 'link' && isset($items[$id]['tab']['#title'])) {
          $items[$id]['tab']['#title'] = $toolbar_items_settings[$id]->custom_label;
        }
        else if ($items[$id]['tab']['#type'] == 'html_tag' && isset($items[$id]['tab']['#value'])) {
          $items[$id]['tab']['#value'] = $toolbar_items_settings[$id]->custom_label;
        }
      }
      if (!empty($toolbar_items_settings[$id]->css_classes) && in_array($items[$id]['tab']['#type'], ['link', 'html_tag'])) {
        $items[$id]['tab']['#attributes']['class'] = explode(' ', $toolbar_items_settings[$id]->css_classes);
      }
    }
  }
}
