toolbar_manager.toolbar_item_settings.*:
  type: config_entity
  label: 'Toolbar Item Settings'
  mapping:
    id:
      type: string
      label: 'Toolbar Item ID'
    enabled:
      type: boolean
      label: 'Enabled'
    weight:
      type: integer
      label: 'Weight'
    custom_label:
      type: string
      label: 'Custom label'
